### ISSUE TITLE
Error: line 4: zscroll: Command not found

### ISSUE THREAD

**Issue by deLini1612** [KairuiLiu/polybar-mpris-control#2]
Hi, thank you for awesome module.
I have an error while auto start this module (I'm using manjaro (arch linux))

I have added this module to polybar (bottom bar) then run it successful manually using command line: `polybar bottom &`

But when I add `exec_always --no-startup-id ~/.config/polybar/launch.sh` to my config file to autorun polybar, when I reboot, this module has an error (like image)
![screenshot-2022 09 12_16:34:43](https://user-images.githubusercontent.com/85008399/189621662-132f474e-d4ae-4612-8774-985e6e68cc46.png)

Can you help me to deal with this error? thank you so much

My launch.sh file:
```
#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch polybar
polybar top &
polybar bottom &
```

**Comment by KairuiLiu** [comment]
Have you installed the [zscroll-git](https://aur.archlinux.org/packages/zscroll-git)? You can try to run `which zscroll` to check out.

**Comment by deLini1612** [comment]
Yes, I have installed zscroll, this is my `which zscroll`
![_000](https://user-images.githubusercontent.com/85008399/189786220-40cdc2ed-5c25-4ae8-947b-f2a4b6ee44d8.png)

If I run lauch.sh by command line (not auto start) `bash  ~/.config/polybar/launch.sh`, it's okay (Result as below)
![name](https://user-images.githubusercontent.com/85008399/189791454-bb56aac3-39a1-4931-ab93-b64a314bdae7.png)

 But when I add to config file to auto start launch.sh, it will occur an error

**Comment by KairuiLiu** [comment]
This is my `launch.sh` you can  try replacing `polybar top &` with `polybar -c <config-file>`
```shell
#!/usr/bin/env sh

## Add this to your wm startup file.

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar1 and bar2
polybar -c ~/.config/polybar/config.ini main
```

**Comment by deLini1612** [comment]
I tried but It still occur same error

**Comment by KairuiLiu** [comment]
try linking zscroll to /bin?

```bash
sudo ln -s /home/.../zscroll /bin
```

if it still not work...I can't do anything

**Comment by deLini1612** [comment]
> try linking zscroll to /bin?
> 
> ```shell
> sudo ln -s /home/.../zscroll /bin
> ```
It solve the problem! Thank you so much for your help
